--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 9.3.930
--   Created On : 星期日, 04 五月, 2014 
--   DBMS       : MySql 
--   -------------------------------------------------- 
use demodb;

SET FOREIGN_KEY_CHECKS=0;

--  Create Tables 
CREATE TABLE BuAddress
(
	Id INT auto_increment NOT NULL,
	AddressName LONGTEXT,
	PRIMARY KEY (Id),
	UNIQUE UQ_address_id(Id)

) COMMENT='地址表';

CREATE TABLE BuBigStationInfo
(
	BigStationId INT AUTO_INCREMENT NOT NULL COMMENT '总站ID',
	BigStationName VARCHAR(150) NOT NULL COMMENT '总站名称',
	BigStationProvince INT NOT NULL COMMENT '所在省份',
	BigStationCity INT NOT NULL COMMENT '所在城市',
	BigSstationAddress INT NOT NULL COMMENT '所在地址',
	PRIMARY KEY (BigStationId),
	UNIQUE UQ_bigstationinfo_bstationid(BigStationId)

)  COMMENT='总站信息表';

CREATE TABLE BuCarInfo
(
	CarNumber VARCHAR(50) NOT NULL COMMENT '车牌号',
	CarName VARCHAR(50) NOT NULL COMMENT '车辆名称',
	CarKind VARCHAR(50) COMMENT '车辆类型',
	CarRemark longtext COMMENT '车辆备注',
	PRIMARY KEY (CarNumber),
	UNIQUE UQ_Carinfo_carnumber(CarNumber)

) COMMENT='车辆信息表';

CREATE TABLE BuCarRepair
(
	RepairId INTEGER NOT NULL COMMENT '检修ID',
	RepairDate DATE NOT NULL COMMENT '检修日期',
	CarNumber VARCHAR(50) NOT NULL COMMENT '检修车牌号',
	DutyOfficer VARCHAR(50) NOT NULL COMMENT '检修负责人',
	RepairComment LONGTEXT NOT NULL COMMENT '检修说明',
	PRIMARY KEY (RepairId),
	UNIQUE UQ_carrepair_repairid(RepairId)

)  COMMENT='车辆检修记录表';

CREATE TABLE BuCityInfo
(
	CityCode VARCHAR(50) NOT NULL COMMENT '城市ID',
	CityName VARCHAR(50) NOT NULL COMMENT '城市名称',
	ProvinceId INT NOT NULL COMMENT '所属省份ID',
	PRIMARY KEY (CityCode)

)  COMMENT='城市信息表';

CREATE TABLE BuGastankInfo 
( 
	TankNumber VARCHAR(100) NOT NULL    COMMENT '气罐编号',
	TankKind VARCHAR(100) NOT NULL   COMMENT '气罐类型',
	TankVolume VARCHAR(100) NOT NULL    COMMENT '气罐容量', 
	Tank1 VARCHAR(100)  COMMENT '预留字段',
	Tank2 VARCHAR(100)   COMMENT '预留字段',
	Tank3 VARCHAR(100)   COMMENT '预留字段',
	PRIMARY KEY (TankNumber),
	UNIQUE UQ_gastank_tanknumber(TankNumber)

)  COMMENT='气罐信息表';

CREATE TABLE BuGastankRepair
(
	GasRepairId INT AUTO_INCREMENT NOT NULL COMMENT '检修信息ID（表）',
	GasRepairDate DATE NOT NULL COMMENT '检修日期',
	TankNumber VARCHAR(50) NOT NULL COMMENT '气罐编号',
	DutyOfficer VARCHAR(50) NOT NULL COMMENT '检修责任人',
	Remark LONGTEXT COMMENT '备注',
	PRIMARY KEY (GasRepairId),
	UNIQUE UQ_gastankrepair_gasrepairid(GasRepairId)

)  COMMENT='气罐检修记录表';

CREATE TABLE BuGPSInfo
(
	GPSId VARCHAR(50) NOT NULL COMMENT 'GPS同步ID',
	SynchronizationType VARCHAR(50) NOT NULL COMMENT '同步类型',
	SynchronizationTime DATETIME NOT NULL COMMENT '同步时间',
	SynchronizationStatus VARCHAR(50) NOT NULL COMMENT '同步状态',
	Longitude VARCHAR(50) NOT NULL COMMENT '经度',
	Latitude VARCHAR(50) NOT NULL COMMENT '纬度',
	CarId INT NOT NULL,
	PRIMARY KEY (GPSId),
	UNIQUE UQ_GPSinfo_gpsid(GPSId)

)  COMMENT='GPS同步信息表';

CREATE TABLE BuGPSLog
(
	GPSLogId INT AUTO_INCREMENT NOT NULL COMMENT 'logoid',
	SynchronizationStatus VARCHAR(50) NOT NULL,
	SynchronizationDate DATETIME NOT NULL COMMENT '同步日期',
	SynchronizationInfo VARCHAR(200) NOT NULL COMMENT '同步信息',
	PRIMARY KEY (GPSLogId),
	UNIQUE UQ_GPSlogo_gpslogoid(GPSLogId)

)  COMMENT='GPS同步日志表';

CREATE TABLE BuKindInfo
(
	KindId INT AUTO_INCREMENT NOT NULL COMMENT '类别ID',
	KindName VARCHAR(50) NOT NULL COMMENT '类别名称',
	PRIMARY KEY (KindId),
	UNIQUE UQ_kindinfo_kindid(KindId)

)  COMMENT='类别信息表';

CREATE TABLE BuPost
(
	PostId INT AUTO_INCREMENT NOT NULL COMMENT '岗位ID',
	PostName VARCHAR(50) NOT NULL COMMENT '岗位名称',
	UserId INT NOT NULL COMMENT '审批人ID',
	UserName VARCHAR(50) NOT NULL COMMENT '用户名称（数据冗余，方便后期检索）',
	PRIMARY KEY (PostId),
	UNIQUE UQ_post_postid(PostId)

)  COMMENT='审批岗位表';

CREATE TABLE BuProvinceInfo
(
	ProvinceCode VARCHAR(50) NOT NULL COMMENT '省份代码',
	ProvinceName VARCHAR(50) NOT NULL COMMENT '身份名称',
	PRIMARY KEY (ProvinceCode),
	UNIQUE UQ_provinceinfo_provinceid(ProvinceCode)

)  COMMENT='省份信息表';

CREATE TABLE BuSchedule
(
	ScheduleId INT AUTO_INCREMENT NOT NULL COMMENT '调度ID',
	ScheduleName VARCHAR(50) NOT NULL COMMENT '调度名称',
	CreateMan VARCHAR(50) NOT NULL COMMENT '调度员',
	CreateDate DATETIME NOT NULL COMMENT '调度日期',
	UpdateMan VARCHAR(50) NOT NULL COMMENT '修改人',
	UpdateDate VARCHAR(50) NOT NULL COMMENT '修改时间',
	ScheduleStatus VARCHAR(5) NOT NULL COMMENT '调度状态',
	ScheduleKind INTEGER NOT NULL COMMENT '调度类型',
	StationId VARCHAR(50) NOT NULL COMMENT '站点',
	StationBossId VARCHAR(50) NOT NULL COMMENT '站长',
	ExecuteDate DATETIME NOT NULL COMMENT '执行日期',
	ApplyDate DATETIME NOT NULL COMMENT '申请日期',
	StartAddress VARCHAR(50) NOT NULL COMMENT '发车地址',
	BigStationId INTEGER NOT NULL COMMENT '总站',
	TakeTime DATETIME NOT NULL COMMENT '路途花费时间',
	AddTime DATETIME NOT NULL COMMENT '冗余时间',
	TargetAddress VARCHAR(50) NOT NULL COMMENT '目标地点',
	NeedTime DATETIME NOT NULL COMMENT '用气时间',
	PRIMARY KEY (ScheduleId),
	UNIQUE UQ_Schedule_Scheduleid(ScheduleId)

)  COMMENT='调度排班表';

CREATE TABLE BuScheduleApply
(
	ApplyId VARCHAR(50) NOT NULL COMMENT '审批ID',
	ApplyMan VARCHAR(50) NOT NULL COMMENT '审批人对应post表中的userid',
	ApplyDate DATETIME NOT NULL COMMENT '审批日期',
	PRIMARY KEY (ApplyId),
	UNIQUE UQ_Scheduleapply_applyid(ApplyId)

)  COMMENT='调度审批表';

CREATE TABLE BuStationInfo
(
	StationId INTEGER AUTO_INCREMENT NOT NULL COMMENT '站点ID',
	StationName VARCHAR(50) NOT NULL COMMENT '站点名称',
	StationBoss VARCHAR(50) NOT NULL COMMENT '站长（扛把子）',
	ProvinceId INT NOT NULL COMMENT '省份id',
	CityId INT NOT NULL COMMENT '城市id',
	Address VARCHAR(100) NOT NULL COMMENT '地址',
	PRIMARY KEY (StationId),
	UNIQUE UQ_stationinfo_stationid(StationId)

)  COMMENT='站点信息表';

CREATE TABLE BuTypeInfo
(
	TypeId INT AUTO_INCREMENT NOT NULL COMMENT '类型ID',
	TypeName VARCHAR(50) NOT NULL COMMENT '类型名称',
	KindId INTEGER NOT NULL COMMENT '类别ID',
	PRIMARY KEY (TypeId),
	UNIQUE UQ_typeinfo_typeid(TypeId)

)  COMMENT='类型信息表';

CREATE TABLE BuWFProcess
(
	ProcessId INT AUTO_INCREMENT NOT NULL COMMENT '节点ID',
	processName VARCHAR(50) NOT NULL COMMENT '节点名称',
	PRIMARY KEY (ProcessId),
	UNIQUE UQ_WFProcess_Processid(ProcessId)

)  COMMENT='节点信息表';

CREATE TABLE BuWFRelationship
(
	RelationshipId INT AUTO_INCREMENT NOT NULL COMMENT 'ID',
	WorkflowGUID VARCHAR(50) NOT NULL COMMENT '流程GUID',
	LastProcessId INT NOT NULL COMMENT '上一步',
	CurProcessId INT NOT NULL COMMENT '当前步骤',
	NextProcessId INT NOT NULL COMMENT '下一步',
	ApprovePostId int NOT NULL COMMENT '审批职位ID',
	ApprovePostName VARCHAR(50) NOT NULL COMMENT '审批职位(冗余)（对迎当前节点）',
	Enable bool  NOT NULL COMMENT '是否启用',
	PRIMARY KEY (RelationshipId),
	UNIQUE UQ_WFrelationship_relationshipid(RelationshipId)

)  COMMENT='流程节点关系表';

CREATE TABLE BuWFRelationshipLog
(
	LogId INT AUTO_INCREMENT NOT NULL COMMENT '日志ID',
	RelationshipId INT NOT NULL COMMENT '审批关系ID',
	Status INTEGER NOT NULL COMMENT '流程状态',
	PRIMARY KEY (LogId),
	UNIQUE UQ_WFrelationshiplogo_logoid(LogId)

)  COMMENT='流程审批日志表';

CREATE TABLE BuWorkFlow
(
	WorkflowGUID VARCHAR(50) NOT NULL COMMENT '流程GUID',
	WorkflowName VARCHAR(50) NOT NULL COMMENT '流程名称',
	PRIMARY KEY (WorkflowGUID),
	UNIQUE UQ_Workflow_Workflowguid(WorkflowGUID)

)  COMMENT='流程表';

CREATE TABLE `ayjz_xxts` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `FSR` varchar(20) DEFAULT NULL COMMENT '发送人',
  `FSSJ` datetime DEFAULT NULL COMMENT '发送时间',
  `FSNR` varchar(200) DEFAULT NULL COMMENT '发送内容',
  `JSR` varchar(20) DEFAULT NULL COMMENT '接收人',
  `QLSJ` datetime DEFAULT NULL COMMENT '处理时间',
  `CLJG` varchar(20) DEFAULT NULL COMMENT '处理结果(0:未解决，1:已解决)',
  `BJ` varchar(2) DEFAULT '0' COMMENT '标志(0:未读，1:已读)',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='站内信';

SET FOREIGN_KEY_CHECKS=1;